# Generated by Django 4.2.5 on 2023-10-07 02:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カレンダー')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='開始日時')),
                ('end', models.DateTimeField(verbose_name='開始日時')),
                ('title', models.CharField(max_length=200)),
                ('repeat', models.PositiveIntegerField(blank=True, null=True, verbose_name='繰り返し期間')),
                ('stop', models.DateTimeField(blank=True, default=datetime.datetime(2026, 7, 3, 2, 25, 33, 956456, tzinfo=datetime.timezone.utc), null=True, verbose_name='繰り返し終了日')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.calendar', verbose_name='スケジュール')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='スケジュール作成者')),
            ],
        ),
        migrations.CreateModel(
            name='CancelRepeatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_dt', models.DateField(verbose_name='キャンセル日時')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.event', verbose_name='紐づくカレンダー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='読み込み権限')),
                ('write', models.BooleanField(default=False, verbose_name='書き込み権限')),
                ('chat', models.BooleanField(default=False, verbose_name='チャット権限')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.calendar', verbose_name='カレンダー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.calendar', verbose_name='カレンダー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='permission',
            field=models.ManyToManyField(blank=True, related_name='calendar_permission', through='schedule.CalendarPermission', to=settings.AUTH_USER_MODEL, verbose_name='公開範囲'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
    ]
